version: '3.1'

services:
  # Postgresql
  db:
    container_name: mygram_db
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  # Pgadmin dashboard
  pgadmin:
    container_name: mygram_dashboard
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=taka@test.com
      - PGADMIN_DEFAULT_PASSWORD=depok001
    depends_on: 
      - db
    ports: 
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
